name: build

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      skip-checkout:
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      if: ${{ !github.event.inputs.skip-checkout }}
      uses: actions/checkout@v3

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 17

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Generate Android.bp
      run: |
        ./gradlew app:generateBp
        if [[ ! -z $(git status -s) ]]; then
          git status
          exit -1
        fi

    - uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
