name: build

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      gerrit-ref:
        type: string
        required: false
      ref:
        type: string
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      if: github.event.inputs.ref == '' || github.event.inputs.gerrit-ref == ''
      uses: actions/checkout@v3

    - name: Checkout repo
      if: github.event.inputs.ref != '' && github.event.inputs.gerrit-ref != ''
      uses: lineageos-infra/fetch-gerrit-change@main
      with:
        repository: ${{ github.repository }}
        gerrit-ref: ${{ inputs.gerrit-ref }}
        ref: ${{ inputs.ref }}

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 17

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Generate Android.bp
      run: |
        ./gradlew app:generateBp
        if [[ ! -z $(git status -s) ]]; then
          git status
          exit -1
        fi

    - uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
