name: gerrit checks

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
      gerrit-ref:
        type: string
      change:
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: lineageos-infra/fetch-gerrit-change@main
      with:
        repository: ${{ github.repository }}
        gerrit-ref: ${{ inputs.gerrit-ref }}
        ref: ${{ inputs.ref }}

    - name: Build
      uses: ./.github/workflows/build

    - uses: lineageos-infra/gerrit-vote@main
      if: success()
      with:
        auth: ${{ secrets.GERRIT_VOTE_CREDS }}
        change: ${{ inputs.change }}
        ref: ${{ inputs.ref }}
        code-review: +1

    - uses: lineageos-infra/gerrit-vote@main
      if: failure()
      with:
        auth: ${{ secrets.GERRIT_VOTE_CREDS }}
        change: ${{ inputs.change }}
        ref: ${{ inputs.ref }}
        code-review: -1
