name: gerrit checks

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
      gerrit-ref:
        type: string
      change:
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: lineageos-infra/fetch-gerrit-change@main
      with:
        repository: LineageOS/android_packages_apps_Aperture
        gerrit-ref: ${{ inputs.gerrit-ref }}
        ref: ${{ inputs.ref }}

    - name: Build
      uses: ./.github/workflows/build
